version: 2
jobs:
  build:
    docker:
      - image: astraluma/entrypoint-debug
    steps:
      - run: 
          command: __STEP_COMMAND_ONE__
          shell: /entrypoint
      - run: 
          command: __STEP_COMMAND_TWO__
          shell: /entrypoint
